### ISSUE TITLE
About `View()` calls in the book

### ISSUE THREAD

**Issue by pat-s** [krlmlr/vistransrep#21]
When rendering the book, all the `View()` calls in the code chunks cause the DF's to open in RStudio. This causes > 10 DF opens per book knit that one needs to close manually which is quite annoying.

Regarding console output, one should just be fine by omitting the `View()` calls, shouldn't it? Is there a specific reason for having them in the pipes shown in the book?

**Comment by krlmlr** [comment]
`s/View/view/g`

**Comment by pat-s** [comment]
Sure, was just wondering if there is a reasoning. I'll do a PR.

**Comment by krlmlr** [comment]
A PR would be great, thanks.
