### ISSUE TITLE
About the "remove-all" chunks

### ISSUE THREAD

**Issue by pat-s** [krlmlr/vistransrep#26]
I constantly get bitten by the following errors

```
processing file: _main.Rmd
Error in parse_block(g[-1], g[1], params.src) : 
  duplicate label '31-remove-all'
Please delete _main.Rmd after you finish debugging the error.
```

even when not including all the `script/` files in the book. How do you deal with that?

Are those `rm(list = ls())` calls really required for a clean book rendering?

**Comment by pat-s** [comment]
Just discovered that this only happens if one calls `bookdown::serve_book()`.

Calling `bookdown::serve_book("book/")` solves it.

**Comment by krlmlr** [comment]
We shouldn't need duplicate chunk names. The "clean all" parts help detect errors.
