### ISSUE TITLE
Horizontal rules cause error when converting to PDF with pandoc 2.7

### ISSUE THREAD

**Issue by pat-s** [krlmlr/vistransrep#32]
The latest texlive update broke horizontal rules (`---`) when converting to PDF.
See here: https://github.com/jgm/pandoc/issues/5801

I like using them and have quite a lot in the vis chapter.

pandoc >= 2.8 should fix it but is not yet released (its awaited daily).

**Comment by krlmlr** [comment]
Works on Travis?

https://krlmlr.github.io/vistransrep/book/vistransrep.pdf

**Comment by pat-s** [comment]
I assume because Travis hasn't the latest Texlive (bionic).

So for now its a local problem of mine and should be resolved when pandoc 2.8 is released. Only bothers for me local PDF comp which isn't a blocker.

**Comment by krlmlr** [comment]
Let's rely on Travis for consistency.

**Comment by yihui** [comment]
FYI I just fixed this issue in **rmarkdown**: https://github.com/rstudio/rmarkdown/commit/2faf16a8bc4755569250fd426b0c5080888de2a0.
