### ISSUE TITLE
Align book outline with time schedule?

### ISSUE THREAD

**Issue by pat-s** [krlmlr/vistransrep#33]
Maybe its good to resolve this once again in written form (see also the discussion in the gdoc)

0. Introduction (incl RStudio)

1. Vis basics 

(lunch day 1)

2. Transformation

3. Vis advanced (facetting + ext)

(lunch day2)

4. Reporting (rmarkdown)

5. Importing (?)

6. Tidying (?)

Maybe we should have another quick call on this?

**Comment by krlmlr** [comment]
I'm not sure the structure of the book needs to reflect the schedule perfectly.

**Comment by pat-s** [comment]
There are always two choices:

1. group logically

1. group by time

Right now we (1). Should we stick with it?
Then I'll just append the advanced ggplot2 part to the vis chapter.

**Comment by krlmlr** [comment]
I'd prefer (1) too.
