### ISSUE TITLE
Use roboto font family?

### ISSUE THREAD

**Issue by pat-s** [krlmlr/vistransrep#37]
Personal preference thing but I find the Roboto font family (as e.g. in https://mlr3book.mlr-org.com/pipelines.html) easier for the eyes when it comes to sans than Helvetica. 

There is also "Roboto Mono" for monospace to stay consistent (current default is Liberation Mono).

**Comment by krlmlr** [comment]
Happy to adapt Roboto.

**Comment by pat-s** [comment]
fixed in 3d92baad320f6844191ca5c26e00785f69c74be9
