### ISSUE TITLE
Fix image width/height of ggplot basic section

### ISSUE THREAD

**Issue by pat-s** [krlmlr/vistransrep#41]
width = 8 and height = 5 work fine.

**Comment by krlmlr** [comment]
And a random forest dies.

**Comment by krlmlr** [comment]
Does it make sense to have different settings for HTML and PDF output?

**Comment by pat-s** [comment]
Not sure, maybe. I do not think I have capacities right now to check for both.

**Comment by krlmlr** [comment]
Fixed now, please make sure it's updated in the branches.
